### ISSUE TITLE
 the codebase for the lora fine-tuning on Magicoder-Evol-Instruct-110K

### ISSUE THREAD

**Issue by lucasliunju** [danbider/lora-tradeoffs#1]
Hi,

Thanks for your great contribution. 

May I ask the codebase for the lora fine-tuning on Magicoder-Evol-Instruct-110K? 

Best

**Comment by jacobfulano** [comment]
Hi @lucasliunju,

We used an internal codebase for finetuning based on [mosaicml/composer ](https://github.com/mosaicml/composer)and [llm-foundry](https://github.com/mosaicml/llm-foundry). However you might be interested in the model weights, which we have released here: [https://huggingface.co/LoRA-TMLR-2024](https://huggingface.co/LoRA-TMLR-2024)
