### ISSUE TITLE
ETA on model checkpoints?

### ISSUE THREAD

**Issue by akshat57** [danbider/lora-tradeoffs#2]
Hi, 

Thanks for your amazing work. We wanted to do a follow-up study on your work and were wondering if there was an ETA on the model checkpoints?

**Comment by jacobfulano** [comment]
Hi @akshat57, 

We've started uploading the model checkpoints here: [https://huggingface.co/LoRA-TMLR-2024](https://huggingface.co/LoRA-TMLR-2024)

All the weights and model cards should be uploaded in the next 1-2 days.

**Comment by jacobfulano** [comment]
The checkpoints for all main experiments have been uploaded here: [https://huggingface.co/LoRA-TMLR-2024](https://huggingface.co/LoRA-TMLR-2024)

Note that intermediate checkpoints are available as well by using the HuggingFace branches for each model. Please let us know if you have any issues

**Comment by akshat57** [comment]
Thank you so much for the prompt response!
